@Cosmo.Api_HostAddress = http://localhost:5203

POST {{Cosmo.Api_HostAddress}}/api/chat/sendMessage
Accept: application/json
Content-Type: application/json

{
  "message": "Hello, how are you?"
}

###
